### ISSUE TITLE
Change the entry of daily working hours at edit user/new user page

### ISSUE THREAD

**Issue by davidurban** [DBJRdev/ditt-client#96]
> We would like to revise this area in its structure. The idea is to be able to enter in one line following content:
> 
> - from (input Month/Year) - to (input Month/Year)
> - working days per week (input a number)
> - working time per week (input a number) = working hours per day/daily working time (as an automatic calculation from working time per week by the days) The result is as before the basis for the daily target's.
> 
> In addition to specifying working days per week, it should be possible to select the days of the week with a checkbox. This should make it possible to work less than five days a week, but you have to select when they are valid. e.g. only three days a week, select Monday, Tuesday, Wednesday the remaining days of the week would have to be treated like a Saturday now.
> 
> If there are changes in the working time, it should then be possible to add a new line with the same input options. The specified period then always determines from when to when it is valid.
> 
> I imagine that it represents a complex change to the previous entry option and working method and is time-consuming. So I would be very interested if you think this is implementable or how. Also with regard to the transferability to our current system and the existing data sets.

**Comment by davidurban** [comment]
The issue discusses user admin view:

<img width="732" alt="Screenshot 2022-06-24 at 15 27 28" src="https://user-images.githubusercontent.com/8739891/175545665-51f0d3a7-e4a7-49fa-8675-d2fbbbadc4c8.png">

**Comment by davidurban** [comment]
Add ability to enter things like 10 hours per week, but only in 2 days.

**Comment by bedrich-schindler** [comment]
@DBJRdev @davidurban @cetcondor As the implementation is quite complicated, I want to check following things. Technically, I implemented following attributes/fields for the single contract:

```
    # Contact structure
        startDateTime:
            type: datetime_immutable
        endDateTime:
            type: datetime_immutable
        isMondayIncluded:
            type: boolean
        isTuesdayIncluded:
            type: boolean
        isWednesdayIncluded:
            type: boolean
        isThursdayIncluded:
            type: boolean
        isFridayIncluded:
            type: boolean
        weeklyWorkingHour:
            type: float
```

It means that HR must enter start and end of the contact, must enter weekly working hours (e.g. 24 hours per week) and select which days are working (e.g. Monday, Wednesday, Friday). Those 24 hours are divided, so employee should work 8 hours a day. Do we need something else?

In assignment, there is defined field `working days per week (input a number)`, but I thing it does not make sense to have such a field if we need to have checkboxes for each day. Do you agree?

Do we want to have nothing selected and working hours set to 0 or do we want to pre-fill it with some standard values, e.g. select all days and pre-fill 40 hours per week?

Do we need to implement checkboxes also Saturday and Sunday or is it prohibited? If it is allowed, we would have to change calculation of worked time.

Should I display non-working days in Monthly logs (Calendar) with gray background as it is with weekends and holidays?

Should I allow user to enter worklog for days that are non-working? Now we allow employees to add work logs even on holidays and weekend so I suppose it does not change. I Just want to make sure.


In the matter of calculuation of worked time, how those non-working days should be exactly treated? Currently, at the end of the calculation, we perform this adjustment:

```  
           // Increase times during sundays and public holidays
            if ($isHoliday($currentDate)) {
                $workTime *= 1.35;
            } elseif ($currentDate->format('l') === 'Sunday') {
                $workTime *= 1.25;
            }
```

If I work on Sunday (not on Saturday!), worked time is multiplied by 1.25, on holidays by 1.35. Should those non-working days be treated as Sunday? What about Saturday, should it be adjusted also?
